if(ENABLE_SDL2)
  find_package(SDL2 2.30.0 REQUIRED)
endif()
if(NOT WIN32 AND NOT ANDROID)
  find_package(CURL REQUIRED)
  find_package(Zstd REQUIRED)
	find_package(WebP REQUIRED)
  find_package(ZLIB REQUIRED)
endif()
if(UNIX AND NOT APPLE)
  find_package(Libbacktrace)
  if(NOT LIBBACKTRACE_FOUND)
    message(WARNING "libbacktrace not found, crashes will not produce backtraces.")
  endif()
endif()
