/* config.h - generated by CMake. */

/* Name of package */
#define PACKAGE "${PROJECT_NAME}"

/* Version number of package */
#define VERSION "${PROJECT_VERSION}"

/* Target processor clips on negative float to int conversion. */
#cmakedefine01 CPU_CLIPS_NEGATIVE

/* Target processor clips on positive float to int conversion. */
#cmakedefine01 CPU_CLIPS_POSITIVE

/* Target processor is big endian. */
#cmakedefine01 CPU_IS_BIG_ENDIAN

/* Target processor is little endian. */
#cmakedefine01 CPU_IS_LITTLE_ENDIAN

/* Define to 1 if you have the `alarm' function. */
#cmakedefine01 HAVE_ALARM

/* Define to 1 if you have the <alsa/asoundlib.h> header file. */
#cmakedefine01 HAVE_ALSA

/* Set to 1 if you have libfftw3. */
#cmakedefine01 HAVE_FFTW3

/* Define if you have C99's lrint function. */
#cmakedefine01 HAVE_LRINT

/* Define if you have C99's lrintf function. */
#cmakedefine01 HAVE_LRINTF

/* Define if you have signal SIGALRM. */
#cmakedefine01 HAVE_SIGALRM

/* Define to 1 if you have the `signal' function. */
#cmakedefine01 HAVE_SIGNAL

/* Set to 1 if you have libsndfile. */
#cmakedefine01 HAVE_SNDFILE

/* Define to 1 if you have the <stdbool.h> header file. */
#cmakedefine HAVE_STDBOOL_H

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine01 HAVE_STDINT_H

/* Define to 1 if you have the <sys/times.h> header file. */
#cmakedefine01 HAVE_SYS_TIMES_H

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H

/* define fast samplerate convertor */
#cmakedefine ENABLE_SINC_FAST_CONVERTER

/* define balanced samplerate convertor */
#cmakedefine ENABLE_SINC_MEDIUM_CONVERTER

/* define best samplerate convertor */
#cmakedefine ENABLE_SINC_BEST_CONVERTER

/* The size of `int', as computed by sizeof. */
#define SIZEOF_INT ${SIZEOF_INT}

/* The size of `long', as computed by sizeof. */
#define SIZEOF_LONG ${SIZEOF_LONG}
