// SPDX-FileCopyrightText: 2019-2024 Connor McLaughlin <stenzek@gmail.com>
// SPDX-License-Identifier: CC-BY-NC-ND-4.0

#define ENUMERATE_LOG_CHANNELS(X)                                                                                      \
  X(Achievements)                                                                                                      \
  X(AudioStream)                                                                                                       \
  X(AutoUpdaterDialog)                                                                                                 \
  X(BIOS)                                                                                                              \
  X(Bus)                                                                                                               \
  X(CDImage)                                                                                                           \
  X(CDROM)                                                                                                             \
  X(CDROMAsyncReader)                                                                                                  \
  X(CPU)                                                                                                               \
  X(Cheats)                                                                                                            \
  X(CodeCache)                                                                                                         \
  X(CompressHelpers)                                                                                                   \
  X(Controller)                                                                                                        \
  X(CubebAudioStream)                                                                                                  \
  X(CueParser)                                                                                                         \
  X(DInputSource)                                                                                                      \
  X(DMA)                                                                                                               \
  X(DynamicLibrary)                                                                                                    \
  X(FileLoader)                                                                                                        \
  X(FileSystem)                                                                                                        \
  X(FullscreenUI)                                                                                                      \
  X(GDBProtocol)                                                                                                       \
  X(GPU)                                                                                                               \
  X(GPUDevice)                                                                                                         \
  X(GPUDump)                                                                                                           \
  X(GPUThread)                                                                                                         \
  X(GPU_SW)                                                                                                            \
  X(GPU_HW)                                                                                                            \
  X(GameDatabase)                                                                                                      \
  X(GameList)                                                                                                          \
  X(HTTPDownloader)                                                                                                    \
  X(Host)                                                                                                              \
  X(ImGuiFullscreen)                                                                                                   \
  X(ImGuiManager)                                                                                                      \
  X(Image)                                                                                                             \
  X(InputManager)                                                                                                      \
  X(InterruptController)                                                                                               \
  X(Log)                                                                                                               \
  X(MDEC)                                                                                                              \
  X(MediaCapture)                                                                                                      \
  X(MemMap)                                                                                                            \
  X(MemoryCard)                                                                                                        \
  X(Multitap)                                                                                                          \
  X(PCDrv)                                                                                                             \
  X(Pad)                                                                                                               \
  X(PerfMon)                                                                                                           \
  X(PlatformMisc)                                                                                                      \
  X(PostProcessing)                                                                                                    \
  X(ProgressCallback)                                                                                                  \
  X(ReShadeFXShader)                                                                                                   \
  X(Recompiler)                                                                                                        \
  X(SDL)                                                                                                               \
  X(SIO)                                                                                                               \
  X(SPU)                                                                                                               \
  X(Settings)                                                                                                          \
  X(SettingsWindow)                                                                                                    \
  X(ShaderGen)                                                                                                         \
  X(Sockets)                                                                                                           \
  X(StateWrapper)                                                                                                      \
  X(System)                                                                                                            \
  X(TTY)                                                                                                               \
  X(Threading)                                                                                                         \
  X(Timers)                                                                                                            \
  X(TimingEvents)                                                                                                      \
  X(Ungrouped)                                                                                                         \
  X(Win32RawInputSource)                                                                                               \
  X(WindowInfo)                                                                                                        \
  X(XInputSource)
