name: 🐧 Linux AppImage

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: "arm64"
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/duckstation/cross-build-arm64:latest

    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0

    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v4.0.2
      with:
        path: ~/deps
        #key: deps ${{ hashFiles('scripts/deps/build-dependencies-linux.sh', 'scripts/deps/build-ffmpeg-linux.sh') }}
        key: deps ${{ hashFiles('scripts/deps/build-dependencies-linux.sh') }}

    - name: Cache Cross Dependencies
      id: cache-cross-deps
      uses: actions/cache@v4.0.2
      with:
        path: ~/deps-arm64
        key: deps-arm64 ${{ hashFiles('scripts/deps/build-dependencies-linux-cross.sh') }}

    - name: Build Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: scripts/deps/build-dependencies-linux.sh "$HOME/deps"

    #- name: Build FFmpeg
    #  if: steps.cache-deps.outputs.cache-hit != 'true'
    #  run: scripts/deps/build-ffmpeg-linux.sh "$HOME/deps"

    - name: Build Cross Dependencies
      if: steps.cache-cross-deps.outputs.cache-hit != 'true'
      run: scripts/deps/build-dependencies-linux-cross.sh "$HOME/deps" "aarch64" "/arm64-chroot" "$HOME/deps-arm64"

    - name: Set Up Toolchain File
      run: |
        cp "$HOME/deps-arm64/toolchain.cmake" "$HOME/toolchain.cmake"
        echo 'set(CMAKE_C_COMPILER clang-18)' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_C_COMPILER_AR llvm-ar-18)' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_C_COMPILER_RANLIB llvm-ranlib-18)' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_CXX_COMPILER clang++-18)' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_CXX_COMPILER_AR llvm-ar-18)' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_CXX_COMPILER_RANLIB llvm-ranlib-18)' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")' >> "$HOME/toolchain.cmake"
        echo 'set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")' >> "$HOME/toolchain.cmake"

    - name: Initialize Build Tag
      run: |
        echo '#pragma once' > src/scmversion/tag.h

    - name: Set Build Tag Asset
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
      run: |
        echo '#define SCM_RELEASE_ASSET "DuckStation-aarch64.AppImage"' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAGS {"latest", "preview"}' >> src/scmversion/tag.h

    - name: Tag as Preview Release
      if: github.ref == 'refs/heads/master'
      run: |
        echo '#define SCM_RELEASE_TAG "preview"' >> src/scmversion/tag.h

    - name: Tag as Rolling Release
      if: github.ref == 'refs/heads/dev'
      run: |
        echo '#define SCM_RELEASE_TAG "latest"' >> src/scmversion/tag.h

    - name: Download Patch Archives
      shell: bash
      run: |
        cd data/resources
        curl -LO "https://github.com/duckstation/chtdb/releases/download/latest/cheats.zip"
        curl -LO "https://github.com/duckstation/chtdb/releases/download/latest/patches.zip"

    - name: Compile Build
      shell: bash
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_TOOLCHAIN_FILE="$HOME/toolchain.cmake" -DLCONVERT_EXE="$HOME/deps/bin/lconvert" -DHOST_MIN_PAGE_SIZE=4096 -DHOST_MAX_PAGE_SIZE=16384 -DHOST_CACHE_LINE_SIZE=64 ..
        cmake --build build --parallel
        scripts/packaging/appimage/make-cross-appimage.sh aarch64 $(realpath build) "$HOME/deps-arm64" "/arm64-chroot" DuckStation-aarch64

    - name: Upload Qt AppImage
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "linux-aarch64-appimage"
        path: "DuckStation-aarch64.AppImage"
