name: 🐧 Linux AppImage

on:
  workflow_call:
  workflow_dispatch:

jobs:
  #build-armhf:
  #  uses: "./.github/workflows/linux-cross-appimage-build.yml"
  #  with:
  #    arch: "armhf"
  #  secrets: inherit
  build-arm64:
    uses: "./.github/workflows/linux-cross-appimage-build.yml"
    with:
      arch: "arm64"
    secrets: inherit
